name: Update badges

permissions:
  contents: write
on:
  schedule:
    # Runs at 2am UTC
    - cron: "0 2 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:       
          CREDLY_USER: simon-stirling
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
